import {nanoid} from 'nanoid';
const db = [
  {
    id: nanoid(),
    isFavorite: false,
    name: 'Freudenberg',
    location: 'Siegerland',
    duration: 'short',
    type: 'culture',
    infos: 'https://www.freudenberg-wirkt.de/',
  },
  {
    id: nanoid(),
    isFavorite: false,
    name: 'Kreidedampfbad',
    location: 'Binz',
    duration: 'vacation',
    type: 'recovery',
    infos: 'https://www.ruegen.de',
  },
  {
    id: nanoid(),
    isFavorite: false,
    name: 'Luftkurort',
    location: 'Mittenwald',
    duration: 'weekend',
    type: 'recovery',
    infos: 'https://alpenwelt-karwendel.de',
  },
  {
    id: nanoid(),
    isFavorite: false,
    name: 'Drei Kilometer Spass',
    location: 'Bremen',
    duration: 'short',
    type: 'nature',
    infos: 'https://bremer-eisverein.de',
  },
  {
    id: nanoid(),
    name: 'Fatbike',
    isFavorite: false,
    location: 'Vogelsberg',
    duration: 'short',
    type: 'sport',
    infos: 'https://koko-pelli.de',
  },
  {
    id: nanoid(),
    isFavorite: false,
    name: 'Stocherkahnrennen',
    location: 'Tübingen',
    duration: 'short',
    type: 'culture',
    infos: 'https://tuebingen-info.de',
  },
  {
    id: nanoid(),
    isFavorite: false,
    name: 'Wattwanderung',
    location: 'Neuwerk',
    duration: 'short',
    type: 'nature',
    infos: 'https://cuxhaven-neuwerk.de',
  },
  {
    id: nanoid(),
    isFavorite: false,
    name: 'Skywalk',
    location: 'Allgäu',
    duration: 'short',
    type: 'sport',
    infos: 'https://skywalk-allgaeu.de',
  },
  {
    id: nanoid(),
    isFavorite: false,
    name: 'Karl-May-Spiele',
    location: 'Bad Segeberg',
    duration: 'weekend',
    type: 'culture',
    infos: 'https://karl-may-spiele.de',
  },
  {
    id: nanoid(),
    isFavorite: false,
    name: 'Lummensprung',
    location: 'Helgoland',
    duration: 'weekend',
    type: 'nature',
    infos: 'https://helgoland.de',
  },
  {
    id: nanoid(),
    isFavorite: false,
    name: 'Wörnitz Flussbad',
    location: 'Oettingen',
    duration: 'short',
    type: 'recovery',
    infos: 'https://oettingen.de/woernitz-flussfreibad',
  },
  {
    id: nanoid(),
    isFavorite: false,
    name: 'Dackelmuseum',
    location: 'Passau',
    duration: 'short',
    type: 'culture',
    infos: 'https://dackelmuseum.de',
  },
  {
    id: nanoid(),
    isFavorite: false,
    name: 'Opern-Festspiele',
    location: 'Heidenheim',
    duration: 'weekend',
    type: 'culture',
    infos: 'https://opernfestspiele.de',
  },
  {
    id: nanoid(),
    isFavorite: false,
    name: 'Blautopf',
    location: 'Blaubeuren',
    duration: 'short',
    type: 'nature',
    infos: 'https://blautopf.de',
  },
  {
    id: nanoid(),
    isFavorite: false,
    name: 'Übernachten im Baumzelt',
    location: 'Witzenhausen',
    duration: 'weekend',
    type: 'nature',
    infos: 'https://robins-nest.de',
  },
  {
    id: nanoid(),
    isFavorite: false,
    name: 'Filmnächte am Elbufer',
    location: 'Dresden',
    duration: 'short',
    type: 'culture',
    infos: 'https://dresden.filmnaechte.de',
  },
  {
    id: nanoid(),
    isFavorite: false,
    name: 'Weisse Düne',
    location: 'Norderney',
    duration: 'vacation',
    type: 'recovery',
    infos: 'https://norderney.de',
  },
  {
    id: nanoid(),
    isFavorite: false,
    name: 'Stoneman Miriquidi',
    location: 'Erzgebirge',
    duration: 'vacation',
    type: 'sport',
    infos: 'https://stoneman-miriquidi.com',
  },
  {
    id: nanoid(),
    isFavorite: false,
    name: 'Schnelle Runden',
    location: 'Nürburgring',
    duration: 'weekend',
    type: 'challenge',
    infos: 'https://nuerburgring.de',
  },
  {
    id: nanoid(),
    isFavorite: false,
    name: 'Flaeming-Skate',
    location: 'Brandenburg',
    duration: 'weekend',
    type: 'sport',
    infos: 'https://flaeming-skate.de',
  },
  {
    id: nanoid(),
    isFavorite: false,
    name: 'Sternschnuppen',
    location: 'Nationalpark Eifel',
    duration: 'weekend',
    type: 'nature',
    infos: 'https://nationalpark-eifel.de/de/nationalpark-erleben/sternenpark',
  },
  {
    id: nanoid(),
    isFavorite: false,
    name: 'Klettern im Ith',
    location: 'Ith',
    duration: 'weekend',
    type: 'challenge',
    infos: 'https://ig-klettern-niedersachsen.de',
  },
  {
    id: nanoid(),
    isFavorite: false,
    name: 'Drachenfels',
    location: 'Königswinter',
    duration: 'short',
    type: 'nature',
    infos: 'https://der-drachenfels.de',
  },
  {
    id: nanoid(),
    isFavorite: false,
    name: 'Noctalis',
    location: 'Bad Segeberg',
    duration: 'short',
    type: 'nature',
    infos: 'https://noctalis.de',
  },
  {
    id: nanoid(),
    isFavorite: false,
    name: 'Hüttentour um den Watzmann',
    location: 'Watzmann',
    duration: 'vacation',
    type: 'challenge',
    infos: 'https://berchtesgaden.de/berge-gipfel/watzmann/watzmann-huettentour',
  },
  {
    id: nanoid(),
    isFavorite: false,
    name: 'Burg Teck',
    location: 'Hohenneuffen',
    duration: 'short',
    type: 'nature',
    infos: 'https://schwaebischealb.org/schloesser-burgen/burg-teck',
  },
  {
    id: nanoid(),
    isFavorite: false,
    name: 'Museum Marta',
    location: 'Herford',
    duration: 'short',
    type: 'culture',
    infos: 'https://marta-herford.de',
  },
  {
    id: nanoid(),
    isFavorite: false,
    name: 'Radfahren im Eichsfeld',
    location: 'Eichsfeld',
    duration: 'vacation',
    type: 'sport',
    infos: 'https://eichsfeld.de',
  },
  {
    id: nanoid(),
    isFavorite: false,
    name: 'Gleitschirmfliegen',
    location: 'Oberstdorf',
    duration: 'short',
    type: 'challenge',
    infos: 'https://ok-bergbahnen.com/aktiv-sport/gleitschirmfliegen',
  },
  {
    id: nanoid(),
    isFavorite: false,
    name: 'DAV-kletter-Zentrum',
    location: 'München',
    duration: 'short',
    type: 'challenge',
    infos: 'https://kbthalkirchen.de',
  },
  {
    id: nanoid(),
    isFavorite: false,
    name: 'Fossilien am Strand',
    location: 'Rügen',
    duration: 'vacation',
    type: 'nature',
    infos: 'https://ruegen.de',
  },
  {
    id: nanoid(),
    isFavorite: false,
    name: 'Rutschenwelt',
    location: 'Erding',
    duration: 'short',
    type: 'recovery',
    infos: 'https://therme-erding.de',
  },
  {
    id: nanoid(),
    isFavorite: false,
    name: 'Hexentanz',
    location: 'Harz',
    duration: 'vacation',
    type: 'culture',
    infos: 'https://harzinfo.de/veranstaltungen/walpurgis-im-harz.html',
  },
];

export default db;
